title: Ruike Wu's Homepage
page-top-title: Ruike Wu
top-section-bg-text: Welcome to my website ！
home-subtitle: Ruike Wu&ensp;|&ensp;吴睿珂
copyright-text: '&copy; Ruike Wu 2025-2026. All Rights Reserved.'
